networks:
  tsa_oa:

services:
  database:
    container_name: database_container
    image: mariadb:13.0.1-rc
    env_file:
      - path: .env
        required: true
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - ./volumes/database:/var/lib/mysql:rw
      - ./init:/docker-entrypoint-initdb.d/:ro
    restart: always
    healthcheck:
      interval: 30s
      retries: 3
      timeout: 30s
      test: ['CMD', 'healthcheck.sh', '--su-mysql', '--connect', '--innodb_initialized']
    networks:
      - tsa_oa

volumes:
  database:
